
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9999
